-- Move outdoor brand autocomplete data from frontend constants into normalized database entities.

create table if not exists public.outdoor_brands (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  display_name text not null,
  normalized_name text not null,
  display_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint outdoor_brands_name_key unique (name)
);

comment on table public.outdoor_brands is 'Global outdoor brand catalog used by inventory items and autocomplete controls';

insert into public.outdoor_brands (name, display_name, normalized_name, display_order)
values
  ('100%', '100%', '100%', 0),
  ('3F UL Gear', '3F UL Gear', '3f ul gear', 1),
  ('5.11 Tactical', '5.11 Tactical', '5.11 tactical', 2),
  ('AEGISMAX', 'AEGISMAX', 'aegismax', 3),
  ('AGV', 'AGV', 'agv', 4),
  ('ALPINT MOUNTAIN', 'ALPINT MOUNTAIN', 'alpint mountain', 5),
  ('ALPS Mountaineering', 'ALPS Mountaineering', 'alps mountaineering', 6),
  ('AOTU', 'AOTU', 'aotu', 7),
  ('ATK', 'ATK', 'atk', 8),
  ('Abel', 'Abel', 'abel', 9),
  ('Abu Garcia', 'Abu Garcia', 'abu garcia', 10),
  ('Acerbis', 'Acerbis', 'acerbis', 11),
  ('Aclima', 'Aclima', 'aclima', 12),
  ('Adidas', 'Adidas', 'adidas', 13),
  ('Adidas Skateboarding', 'Adidas Skateboarding', 'adidas skateboarding', 14),
  ('Adidas Terrex', 'Adidas Terrex', 'adidas terrex', 15),
  ('Advanced Elements', 'Advanced Elements', 'advanced elements', 16),
  ('Ahrex', 'Ahrex', 'ahrex', 17),
  ('Ailunce', 'Ailunce', 'ailunce', 18),
  ('Aimpoint', 'Aimpoint', 'aimpoint', 19),
  ('Airflo', 'Airflo', 'airflo', 20),
  ('Airoh', 'Airoh', 'airoh', 21),
  ('Alexika', 'Alexika', 'alexika', 22),
  ('Alpinestars', 'Alpinestars', 'alpinestars', 23),
  ('Alps Mountaineering', 'Alps Mountaineering', 'alps mountaineering', 24),
  ('Altra', 'Altra', 'altra', 25),
  ('Amazon Basics', 'Amazon Basics', 'amazon basics', 26),
  ('Amnesia', 'Amnesia', 'amnesia', 27),
  ('Anker', 'Anker', 'anker', 28),
  ('Anon', 'Anon', 'anon', 29),
  ('Answer Racing', 'Answer Racing', 'answer racing', 30),
  ('Antron', 'Antron', 'antron', 31),
  ('Anytone', 'Anytone', 'anytone', 32),
  ('Apidura', 'Apidura', 'apidura', 33),
  ('Apple', 'Apple', 'apple', 34),
  ('Aqua', 'Aqua', 'aqua', 35),
  ('Aqua Products', 'Aqua Products', 'aqua products', 36),
  ('Aqua-Bound', 'Aqua-Bound', 'aqua-bound', 37),
  ('AquaTech', 'AquaTech', 'aquatech', 38),
  ('Aquamira', 'Aquamira', 'aquamira', 39),
  ('Arai', 'Arai', 'arai', 40),
  ('Arbor', 'Arbor', 'arbor', 41),
  ('Arc''teryx', 'Arc''teryx', 'arc''teryx', 42),
  ('Arca-Swiss', 'Arca-Swiss', 'arca-swiss', 43),
  ('Arva', 'Arva', 'arva', 44),
  ('Asolo', 'Asolo', 'asolo', 45),
  ('Astral', 'Astral', 'astral', 46),
  ('Atlas', 'Atlas', 'atlas', 47),
  ('Atomic', 'Atomic', 'atomic', 48),
  ('AustriAlpin', 'AustriAlpin', 'austrialpin', 49),
  ('Avid Carp', 'Avid Carp', 'avid carp', 50),
  ('B&G', 'B&G', 'b&g', 51),
  ('BASK', 'BASK', 'bask', 52),
  ('BCA', 'BCA', 'bca', 53),
  ('BKK', 'BKK', 'bkk', 54),
  ('BRS', 'BRS', 'brs', 55),
  ('Bach', 'Bach', 'bach', 56),
  ('Badlands', 'Badlands', 'badlands', 57),
  ('Bahco', 'Bahco', 'bahco', 58),
  ('Bajio', 'Bajio', 'bajio', 59),
  ('Balega', 'Balega', 'balega', 60),
  ('Balzer', 'Balzer', 'balzer', 61),
  ('Baofeng', 'Baofeng', 'baofeng', 62),
  ('Barbless', 'Barbless', 'barbless', 63),
  ('Bask', 'Bask', 'bask', 64),
  ('Bass Pro Shops', 'Bass Pro Shops', 'bass pro shops', 65),
  ('Bauer', 'Bauer', 'bauer', 66),
  ('Beal', 'Beal', 'beal', 67),
  ('Bell', 'Bell', 'bell', 68),
  ('Benchmade', 'Benchmade', 'benchmade', 69),
  ('Bending Branches', 'Bending Branches', 'bending branches', 70),
  ('Benelli', 'Benelli', 'benelli', 71),
  ('Benro', 'Benro', 'benro', 72),
  ('Bent Metal', 'Bent Metal', 'bent metal', 73),
  ('Beretta', 'Beretta', 'beretta', 74),
  ('Bergans', 'Bergans', 'bergans', 75),
  ('Bering', 'Bering', 'bering', 76),
  ('Berkley', 'Berkley', 'berkley', 77),
  ('Berkley PowerBait', 'Berkley PowerBait', 'berkley powerbait', 78),
  ('Bern', 'Bern', 'bern', 79),
  ('Big Agnes', 'Big Agnes', 'big agnes', 80),
  ('Billingham', 'Billingham', 'billingham', 81),
  ('BioLite', 'BioLite', 'biolite', 82),
  ('Black Deer', 'Black Deer', 'black deer', 83),
  ('Black Diamond', 'Black Diamond', 'black diamond', 84),
  ('Blackmagic Design', 'Blackmagic Design', 'blackmagic design', 85),
  ('Blaser', 'Blaser', 'blaser', 86),
  ('Blizzard', 'Blizzard', 'blizzard', 87),
  ('Blue Fox', 'Blue Fox', 'blue fox', 88),
  ('Bobbie''s Boat', 'Bobbie''s Boat', 'bobbie''s boat', 89),
  ('Borah Gear', 'Borah Gear', 'borah gear', 90),
  ('Boreal', 'Boreal', 'boreal', 91),
  ('Boundless Voyage', 'Boundless Voyage', 'boundless voyage', 92),
  ('Bozeman', 'Bozeman', 'bozeman', 93),
  ('BridgeCom', 'BridgeCom', 'bridgecom', 94),
  ('Bridgedale', 'Bridgedale', 'bridgedale', 95),
  ('Brooks', 'Brooks', 'brooks', 96),
  ('Browning', 'Browning', 'browning', 97),
  ('Brunton', 'Brunton', 'brunton', 98),
  ('Buck', 'Buck', 'buck', 99),
  ('Buff', 'Buff', 'buff', 100),
  ('Bulin', 'Bulin', 'bulin', 101),
  ('Burris', 'Burris', 'burris', 102),
  ('Burton', 'Burton', 'burton', 103),
  ('Bushnell', 'Bushnell', 'bushnell', 104),
  ('Butora', 'Butora', 'butora', 105),
  ('Böker', 'Böker', 'böker', 106),
  ('C.A.M.P.', 'C.A.M.P.', 'c.a.m.p.', 107),
  ('CAMP', 'CAMP', 'camp', 108),
  ('CC Moore', 'CC Moore', 'cc moore', 109),
  ('CMC Rescue', 'CMC Rescue', 'cmc rescue', 110),
  ('CNOC Outdoors', 'CNOC Outdoors', 'cnoc outdoors', 111),
  ('CRKT', 'CRKT', 'crkt', 112),
  ('CZ', 'CZ', 'cz', 113),
  ('Cabela''s', 'Cabela''s', 'cabela''s', 114),
  ('Caberg', 'Caberg', 'caberg', 115),
  ('Caesar Guerini', 'Caesar Guerini', 'caesar guerini', 116),
  ('Calcutta', 'Calcutta', 'calcutta', 117),
  ('CamelBak', 'CamelBak', 'camelbak', 118),
  ('Camp', 'Camp', 'camp', 119),
  ('Camppal', 'Camppal', 'camppal', 120),
  ('Canon', 'Canon', 'canon', 121),
  ('Capita', 'Capita', 'capita', 122),
  ('Cascade Mountain Tech', 'Cascade Mountain Tech', 'cascade mountain tech', 123),
  ('Case', 'Case', 'case', 124),
  ('Cassin', 'Cassin', 'cassin', 125),
  ('Charlet Moser', 'Charlet Moser', 'charlet moser', 126),
  ('Chinook', 'Chinook', 'chinook', 127),
  ('Chris Reeve', 'Chris Reeve', 'chris reeve', 128),
  ('Chrome', 'Chrome', 'chrome', 129),
  ('Chronos', 'Chronos', 'chronos', 130),
  ('Chub', 'Chub', 'chub', 131),
  ('Circle Hook Co', 'Circle Hook Co', 'circle hook co', 132),
  ('Climb X', 'Climb X', 'climb x', 133),
  ('Climbing Technology', 'Climbing Technology', 'climbing technology', 134),
  ('Cobra', 'Cobra', 'cobra', 135),
  ('Cocoons', 'Cocoons', 'cocoons', 136),
  ('Coghlan''s', 'Coghlan''s', 'coghlan''s', 137),
  ('Coghlans', 'Coghlans', 'coghlans', 138),
  ('Cold Steel', 'Cold Steel', 'cold steel', 139),
  ('Coleman', 'Coleman', 'coleman', 140),
  ('Colltex', 'Colltex', 'colltex', 141),
  ('Colmic', 'Colmic', 'colmic', 142),
  ('Compass 360', 'Compass 360', 'compass 360', 143),
  ('Condor', 'Condor', 'condor', 144),
  ('Contour', 'Contour', 'contour', 145),
  ('Corona', 'Corona', 'corona', 146),
  ('Coros', 'Coros', 'coros', 147),
  ('Cortland', 'Cortland', 'cortland', 148),
  ('Costa Del Mar', 'Costa Del Mar', 'costa del mar', 149),
  ('Crazy Creek', 'Crazy Creek', 'crazy creek', 150),
  ('Creeper', 'Creeper', 'creeper', 151),
  ('Crimson Trace', 'Crimson Trace', 'crimson trace', 152),
  ('Cumulus', 'Cumulus', 'cumulus', 153),
  ('Cycra', 'Cycra', 'cycra', 154),
  ('Cygnet', 'Cygnet', 'cygnet', 155),
  ('DAM', 'DAM', 'dam', 156),
  ('DC Shoes', 'DC Shoes', 'dc shoes', 157),
  ('DJI', 'DJI', 'dji', 158),
  ('DMM', 'DMM', 'dmm', 159),
  ('DVL', 'DVL', 'dvl', 160),
  ('Dagger', 'Dagger', 'dagger', 161),
  ('Daiichi', 'Daiichi', 'daiichi', 162),
  ('Dainese', 'Dainese', 'dainese', 163),
  ('Daiwa', 'Daiwa', 'daiwa', 164),
  ('Danielsson', 'Danielsson', 'danielsson', 165),
  ('Danner', 'Danner', 'danner', 166),
  ('Darn Tough', 'Darn Tough', 'darn tough', 167),
  ('Decathlon', 'Decathlon', 'decathlon', 168),
  ('Decoy', 'Decoy', 'decoy', 169),
  ('Defeet', 'Defeet', 'defeet', 170),
  ('Demon', 'Demon', 'demon', 171),
  ('Deps', 'Deps', 'deps', 172),
  ('Deuter', 'Deuter', 'deuter', 173),
  ('Devold', 'Devold', 'devold', 174),
  ('DiCAPac', 'DiCAPac', 'dicapac', 175),
  ('Didriksons', 'Didriksons', 'didriksons', 176),
  ('Domke', 'Domke', 'domke', 177),
  ('Dr. Slick', 'Dr. Slick', 'dr. slick', 178),
  ('Dragon', 'Dragon', 'dragon', 179),
  ('Drake', 'Drake', 'drake', 180),
  ('Drennan', 'Drennan', 'drennan', 181),
  ('Durston', 'Durston', 'durston', 182),
  ('Dynafit', 'Dynafit', 'dynafit', 183),
  ('Dynamite Baits', 'Dynamite Baits', 'dynamite baits', 184),
  ('ENO', 'ENO', 'eno', 185),
  ('EOTech', 'EOTech', 'eotech', 186),
  ('EP Fibers', 'EP Fibers', 'ep fibers', 187),
  ('ESEE', 'ESEE', 'esee', 188),
  ('ESP', 'ESP', 'esp', 189),
  ('EVS Sports', 'EVS Sports', 'evs sports', 190),
  ('Eagle Claw', 'Eagle Claw', 'eagle claw', 191),
  ('Eagle Creek', 'Eagle Creek', 'eagle creek', 192),
  ('Eberlestock', 'Eberlestock', 'eberlestock', 193),
  ('Echo', 'Echo', 'echo', 194),
  ('Edelrid', 'Edelrid', 'edelrid', 195),
  ('Edelweiss', 'Edelweiss', 'edelweiss', 196),
  ('Einarsson', 'Einarsson', 'einarsson', 197),
  ('Element', 'Element', 'element', 198),
  ('Emerica', 'Emerica', 'emerica', 199),
  ('Emerson', 'Emerson', 'emerson', 200),
  ('Enduro Engineering', 'Enduro Engineering', 'enduro engineering', 201),
  ('Enlightened Equipment', 'Enlightened Equipment', 'enlightened equipment', 202),
  ('Enterprise Tackle', 'Enterprise Tackle', 'enterprise tackle', 203),
  ('Eppinger', 'Eppinger', 'eppinger', 204),
  ('Equip', 'Equip', 'equip', 205),
  ('Esbit', 'Esbit', 'esbit', 206),
  ('Esee', 'Esee', 'esee', 207),
  ('Estes Park', 'Estes Park', 'estes park', 208),
  ('Etekcity', 'Etekcity', 'etekcity', 209),
  ('Etnies', 'Etnies', 'etnies', 210),
  ('Eureka', 'Eureka', 'eureka', 211),
  ('Evernew', 'Evernew', 'evernew', 212),
  ('Evolv', 'Evolv', 'evolv', 213),
  ('Ewa-Marine', 'Ewa-Marine', 'ewa-marine', 214),
  ('Ewing', 'Ewing', 'ewing', 215),
  ('Exped', 'Exped', 'exped', 216),
  ('Extrema Ratio', 'Extrema Ratio', 'extrema ratio', 217),
  ('F-Stop', 'F-Stop', 'f-stop', 218),
  ('FACECOZY', 'FACECOZY', 'facecozy', 219),
  ('FN Herstal', 'FN Herstal', 'fn herstal', 220),
  ('Falcon', 'Falcon', 'falcon', 221),
  ('Fallkniven', 'Fallkniven', 'fallkniven', 222),
  ('Farm to Feet', 'Farm to Feet', 'farm to feet', 223),
  ('Favorite', 'Favorite', 'favorite', 224),
  ('Feathered Friends', 'Feathered Friends', 'feathered friends', 225),
  ('Feeder Concept', 'Feeder Concept', 'feeder concept', 226),
  ('Fenix', 'Fenix', 'fenix', 227),
  ('Fenwick', 'Fenwick', 'fenwick', 228),
  ('Filson', 'Filson', 'filson', 229),
  ('Fire-Maple', 'Fire-Maple', 'fire-maple', 230),
  ('Fireline', 'Fireline', 'fireline', 231),
  ('First Lite', 'First Lite', 'first lite', 232),
  ('Fischer', 'Fischer', 'fischer', 233),
  ('Fish-Skull', 'Fish-Skull', 'fish-skull', 234),
  ('Fisherman', 'Fisherman', 'fisherman', 235),
  ('Fishpond', 'Fishpond', 'fishpond', 236),
  ('Fiskars', 'Fiskars', 'fiskars', 237),
  ('Fits', 'Fits', 'fits', 238),
  ('Five Ten', 'Five Ten', 'five ten', 239),
  ('Fixe', 'Fixe', 'fixe', 240),
  ('Fjallraven', 'Fjallraven', 'fjallraven', 241),
  ('Fjällräven', 'Fjällräven', 'fjällräven', 242),
  ('Flame''s Creed', 'Flame''s Creed', 'flame''s creed', 243),
  ('Flashabou', 'Flashabou', 'flashabou', 244),
  ('Fluorocarbon', 'Fluorocarbon', 'fluorocarbon', 245),
  ('Flux', 'Flux', 'flux', 246),
  ('Fly Racing', 'Fly Racing', 'fly racing', 247),
  ('Fly Scene', 'Fly Scene', 'fly scene', 248),
  ('Flying Fisherman', 'Flying Fisherman', 'flying fisherman', 249),
  ('Forclaz', 'Forclaz', 'forclaz', 250),
  ('Forma', 'Forma', 'forma', 251),
  ('Fortis', 'Fortis', 'fortis', 252),
  ('Fox International', 'Fox International', 'fox international', 253),
  ('Fox Knives', 'Fox Knives', 'fox knives', 254),
  ('Fox Racing', 'Fox Racing', 'fox racing', 255),
  ('Fox Rage', 'Fox Rage', 'fox rage', 256),
  ('Fox River', 'Fox River', 'fox river', 257),
  ('Franchi', 'Franchi', 'franchi', 258),
  ('Frank Thomas', 'Frank Thomas', 'frank thomas', 259),
  ('Fritschi', 'Fritschi', 'fritschi', 260),
  ('Frogg Toggs', 'Frogg Toggs', 'frogg toggs', 261),
  ('Frogs Fanny', 'Frogs Fanny', 'frogs fanny', 262),
  ('Fudo', 'Fudo', 'fudo', 263),
  ('Fujifilm', 'Fujifilm', 'fujifilm', 264),
  ('Fulling Mill', 'Fulling Mill', 'fulling mill', 265),
  ('Furuno', 'Furuno', 'furuno', 266),
  ('Furygan', 'Furygan', 'furygan', 267),
  ('G.Loomis', 'G.Loomis', 'g.loomis', 268),
  ('G3', 'G3', 'g3', 269),
  ('GNU', 'GNU', 'gnu', 270),
  ('GORUCK', 'GORUCK', 'goruck', 271),
  ('GSI Outdoors', 'GSI Outdoors', 'gsi outdoors', 272),
  ('Gaerne', 'Gaerne', 'gaerne', 273),
  ('Galvan', 'Galvan', 'galvan', 274),
  ('Gamakatsu', 'Gamakatsu', 'gamakatsu', 275),
  ('Ganzo', 'Ganzo', 'ganzo', 276),
  ('Gardner Tackle', 'Gardner Tackle', 'gardner tackle', 277),
  ('Garmin', 'Garmin', 'garmin', 278),
  ('Garmont', 'Garmont', 'garmont', 279),
  ('Gary Yamamoto', 'Gary Yamamoto', 'gary yamamoto', 280),
  ('Gehrke''s', 'Gehrke''s', 'gehrke''s', 281),
  ('Geigerrig', 'Geigerrig', 'geigerrig', 282),
  ('Gerber', 'Gerber', 'gerber', 283),
  ('Gerbing', 'Gerbing', 'gerbing', 284),
  ('Giant Loop', 'Giant Loop', 'giant loop', 285),
  ('Girl', 'Girl', 'girl', 286),
  ('Giro', 'Giro', 'giro', 287),
  ('Gitzo', 'Gitzo', 'gitzo', 288),
  ('Givi', 'Givi', 'givi', 289),
  ('Glock', 'Glock', 'glock', 290),
  ('GoPro', 'GoPro', 'gopro', 291),
  ('Goal Zero', 'Goal Zero', 'goal zero', 292),
  ('Gossamer Gear', 'Gossamer Gear', 'gossamer gear', 293),
  ('Grand Trunk', 'Grand Trunk', 'grand trunk', 294),
  ('Granite Gear', 'Granite Gear', 'granite gear', 295),
  ('Grayl', 'Grayl', 'grayl', 296),
  ('Green Glade', 'Green Glade', 'green glade', 297),
  ('Gregory', 'Gregory', 'gregory', 298),
  ('Grex', 'Grex', 'grex', 299),
  ('Greys', 'Greys', 'greys', 300),
  ('Griffin', 'Griffin', 'griffin', 301),
  ('Grivel', 'Grivel', 'grivel', 302),
  ('Grundens', 'Grundens', 'grundens', 303),
  ('Gränsfors Bruk', 'Gränsfors Bruk', 'gränsfors bruk', 304),
  ('Guideline', 'Guideline', 'guideline', 305),
  ('Gulp', 'Gulp', 'gulp', 306),
  ('Guru', 'Guru', 'guru', 307),
  ('HECS', 'HECS', 'hecs', 308),
  ('HJC', 'HJC', 'hjc', 309),
  ('Haglöfs', 'Haglöfs', 'haglöfs', 310),
  ('Halti', 'Halti', 'halti', 311),
  ('Halvarssons', 'Halvarssons', 'halvarssons', 312),
  ('Hanwag', 'Hanwag', 'hanwag', 313),
  ('Hardy', 'Hardy', 'hardy', 314),
  ('Hareline', 'Hareline', 'hareline', 315),
  ('Hasselblad', 'Hasselblad', 'hasselblad', 316),
  ('Hatch', 'Hatch', 'hatch', 317),
  ('Hawke', 'Hawke', 'hawke', 318),
  ('Hayabusa', 'Hayabusa', 'hayabusa', 319),
  ('Head', 'Head', 'head', 320),
  ('Heckler & Koch', 'Heckler & Koch', 'heckler & koch', 321),
  ('Held', 'Held', 'held', 322),
  ('Helinox', 'Helinox', 'helinox', 323),
  ('Helios', 'Helios', 'helios', 324),
  ('Helle', 'Helle', 'helle', 325),
  ('Helly Hansen', 'Helly Hansen', 'helly hansen', 326),
  ('Hends', 'Hends', 'hends', 327),
  ('Henry', 'Henry', 'henry', 328),
  ('Hepco & Becker', 'Hepco & Becker', 'hepco & becker', 329),
  ('Hewolf', 'Hewolf', 'hewolf', 330),
  ('High Sierra', 'High Sierra', 'high sierra', 331),
  ('Hill People Gear', 'Hill People Gear', 'hill people gear', 332),
  ('Hilleberg', 'Hilleberg', 'hilleberg', 333),
  ('Hillman', 'Hillman', 'hillman', 334),
  ('Hillsound', 'Hillsound', 'hillsound', 335),
  ('Hinderer', 'Hinderer', 'hinderer', 336),
  ('Hobie', 'Hobie', 'hobie', 337),
  ('Hoka One One', 'Hoka One One', 'hoka one one', 338),
  ('Holosun', 'Holosun', 'holosun', 339),
  ('Houdini', 'Houdini', 'houdini', 340),
  ('Hultafors', 'Hultafors', 'hultafors', 341),
  ('Humminbird', 'Humminbird', 'humminbird', 342),
  ('Husqvarna', 'Husqvarna', 'husqvarna', 343),
  ('HydraPak', 'HydraPak', 'hydrapak', 344),
  ('Hydro Flask', 'Hydro Flask', 'hydro flask', 345),
  ('Hyperlite Mountain Gear', 'Hyperlite Mountain Gear', 'hyperlite mountain gear', 346),
  ('IOR', 'IOR', 'ior', 347),
  ('IXS', 'IXS', 'ixs', 348),
  ('Ibex', 'Ibex', 'ibex', 349),
  ('Icebreaker', 'Icebreaker', 'icebreaker', 350),
  ('Icepeak', 'Icepeak', 'icepeak', 351),
  ('Icom', 'Icom', 'icom', 352),
  ('InReach', 'InReach', 'inreach', 353),
  ('Inforce', 'Inforce', 'inforce', 354),
  ('Injinji', 'Injinji', 'injinji', 355),
  ('Inov-8', 'Inov-8', 'inov-8', 356),
  ('Insta360', 'Insta360', 'insta360', 357),
  ('Ixon', 'Ixon', 'ixon', 358),
  ('JRC', 'JRC', 'jrc', 359),
  ('Jack Wolfskin', 'Jack Wolfskin', 'jack wolfskin', 360),
  ('JetBoil', 'JetBoil', 'jetboil', 361),
  ('Jig Force', 'Jig Force', 'jig force', 362),
  ('Jobu Design', 'Jobu Design', 'jobu design', 363),
  ('Jones', 'Jones', 'jones', 364),
  ('Julbo', 'Julbo', 'julbo', 365),
  ('Just1', 'Just1', 'just1', 366),
  ('K2', 'K2', 'k2', 367),
  ('Ka-Bar', 'Ka-Bar', 'ka-bar', 368),
  ('Kaenon', 'Kaenon', 'kaenon', 369),
  ('Kahles', 'Kahles', 'kahles', 370),
  ('Kahtoola', 'Kahtoola', 'kahtoola', 371),
  ('Kailas', 'Kailas', 'kailas', 372),
  ('Kamasan', 'Kamasan', 'kamasan', 373),
  ('Kappa', 'Kappa', 'kappa', 374),
  ('Kari Traa', 'Kari Traa', 'kari traa', 375),
  ('Karrimor', 'Karrimor', 'karrimor', 376),
  ('Katabatic', 'Katabatic', 'katabatic', 377),
  ('Katadyn', 'Katadyn', 'katadyn', 378),
  ('Katsuichi', 'Katsuichi', 'katsuichi', 379),
  ('Keen', 'Keen', 'keen', 380),
  ('Keis', 'Keis', 'keis', 381),
  ('Kelty', 'Kelty', 'kelty', 382),
  ('Kenwood', 'Kenwood', 'kenwood', 383),
  ('Kershaw', 'Kershaw', 'kershaw', 384),
  ('Kifaru', 'Kifaru', 'kifaru', 385),
  ('Kirk', 'Kirk', 'kirk', 386),
  ('Klean Kanteen', 'Klean Kanteen', 'klean kanteen', 387),
  ('Klim', 'Klim', 'klim', 388),
  ('Klymit', 'Klymit', 'klymit', 389),
  ('Klättermusen', 'Klättermusen', 'klättermusen', 390),
  ('Kokatat', 'Kokatat', 'kokatat', 391),
  ('Kong', 'Kong', 'kong', 392),
  ('Korda', 'Korda', 'korda', 393),
  ('Korum', 'Korum', 'korum', 394),
  ('Kovea', 'Kovea', 'kovea', 395),
  ('Kriega', 'Kriega', 'kriega', 396),
  ('Krieghoff', 'Krieghoff', 'krieghoff', 397),
  ('Kryptek', 'Kryptek', 'kryptek', 398),
  ('Krystal Flash', 'Krystal Flash', 'krystal flash', 399),
  ('Kuiu', 'Kuiu', 'kuiu', 400),
  ('Kühl', 'Kühl', 'kühl', 401),
  ('LS2', 'LS2', 'ls2', 402),
  ('La Sportiva', 'La Sportiva', 'la sportiva', 403),
  ('Lamiglas', 'Lamiglas', 'lamiglas', 404),
  ('Lamson', 'Lamson', 'lamson', 405),
  ('Landyachtz', 'Landyachtz', 'landyachtz', 406),
  ('Lanshan', 'Lanshan', 'lanshan', 407),
  ('Lazer Sharp', 'Lazer Sharp', 'lazer sharp', 408),
  ('Leatherman', 'Leatherman', 'leatherman', 409),
  ('Leatt', 'Leatt', 'leatt', 410),
  ('Ledlenser', 'Ledlenser', 'ledlenser', 411),
  ('Leeda', 'Leeda', 'leeda', 412),
  ('Leica', 'Leica', 'leica', 413),
  ('Leupold', 'Leupold', 'leupold', 414),
  ('Lib Tech', 'Lib Tech', 'lib tech', 415),
  ('LifeStraw', 'LifeStraw', 'lifestraw', 416),
  ('Light My Fire', 'Light My Fire', 'light my fire', 417),
  ('Lindstrands', 'Lindstrands', 'lindstrands', 418),
  ('LionSteel', 'LionSteel', 'lionsteel', 419),
  ('LiteAF', 'LiteAF', 'liteaf', 420),
  ('Lixada', 'Lixada', 'lixada', 421),
  ('Loaded', 'Loaded', 'loaded', 422),
  ('Lobaev Arms', 'Lobaev Arms', 'lobaev arms', 423),
  ('Look', 'Look', 'look', 424),
  ('Loon Outdoors', 'Loon Outdoors', 'loon outdoors', 425),
  ('Loop', 'Loop', 'loop', 426),
  ('Lorpen', 'Lorpen', 'lorpen', 427),
  ('Lowa', 'Lowa', 'lowa', 428),
  ('Lowe Alpine', 'Lowe Alpine', 'lowe alpine', 429),
  ('Lowepro', 'Lowepro', 'lowepro', 430),
  ('Lowrance', 'Lowrance', 'lowrance', 431),
  ('Lucky Craft', 'Lucky Craft', 'lucky craft', 432),
  ('Lundhags', 'Lundhags', 'lundhags', 433),
  ('MAP', 'MAP', 'map', 434),
  ('MIER', 'MIER', 'mier', 435),
  ('MSR', 'MSR', 'msr', 436),
  ('MT Helmets', 'MT Helmets', 'mt helmets', 437),
  ('Macna', 'Macna', 'macna', 438),
  ('Mad Rock', 'Mad Rock', 'mad rock', 439),
  ('Magellan', 'Magellan', 'magellan', 440),
  ('Mainline Baits', 'Mainline Baits', 'mainline baits', 441),
  ('Mammut', 'Mammut', 'mammut', 442),
  ('Manfrotto', 'Manfrotto', 'manfrotto', 443),
  ('March', 'March', 'march', 444),
  ('Marker', 'Marker', 'marker', 445),
  ('Marlin', 'Marlin', 'marlin', 446),
  ('Marmot', 'Marmot', 'marmot', 447),
  ('Matrix', 'Matrix', 'matrix', 448),
  ('Maui Jim', 'Maui Jim', 'maui jim', 449),
  ('Maven', 'Maven', 'maven', 450),
  ('Maver', 'Maver', 'maver', 451),
  ('Maxima', 'Maxima', 'maxima', 452),
  ('Maxpedition', 'Maxpedition', 'maxpedition', 453),
  ('Mayfly', 'Mayfly', 'mayfly', 454),
  ('Megabass', 'Megabass', 'megabass', 455),
  ('Meindl', 'Meindl', 'meindl', 456),
  ('Meopta', 'Meopta', 'meopta', 457),
  ('Mepps', 'Mepps', 'mepps', 458),
  ('Merkel', 'Merkel', 'merkel', 459),
  ('Merrell', 'Merrell', 'merrell', 460),
  ('Method Feeder', 'Method Feeder', 'method feeder', 461),
  ('Metolius', 'Metolius', 'metolius', 462),
  ('Microtech', 'Microtech', 'microtech', 463),
  ('Middy', 'Middy', 'middy', 464),
  ('Midland', 'Midland', 'midland', 465),
  ('Mikado', 'Mikado', 'mikado', 466),
  ('Mindshift Gear', 'Mindshift Gear', 'mindshift gear', 467),
  ('Minox', 'Minox', 'minox', 468),
  ('Minus33', 'Minus33', 'minus33', 469),
  ('Mobi Garden', 'Mobi Garden', 'mobi garden', 470),
  ('Monster Energy', 'Monster Energy', 'monster energy', 471),
  ('Montana Fly Company', 'Montana Fly Company', 'montana fly company', 472),
  ('Montane', 'Montane', 'montane', 473),
  ('Montbell', 'Montbell', 'montbell', 474),
  ('Moon Lence', 'Moon Lence', 'moon lence', 475),
  ('Mora', 'Mora', 'mora', 476),
  ('Morakniv', 'Morakniv', 'morakniv', 477),
  ('Mosko Moto', 'Mosko Moto', 'mosko moto', 478),
  ('Mossberg', 'Mossberg', 'mossberg', 479),
  ('Mossy Oak', 'Mossy Oak', 'mossy oak', 480),
  ('Motorola', 'Motorola', 'motorola', 481),
  ('Mountain Hardwear', 'Mountain Hardwear', 'mountain hardwear', 482),
  ('Mountain Laurel Designs', 'Mountain Laurel Designs', 'mountain laurel designs', 483),
  ('Movement', 'Movement', 'movement', 484),
  ('Mustad', 'Mustad', 'mustad', 485),
  ('Mystery Ranch', 'Mystery Ranch', 'mystery ranch', 486),
  ('NRS', 'NRS', 'nrs', 487),
  ('Nalgene', 'Nalgene', 'nalgene', 488),
  ('Nash', 'Nash', 'nash', 489),
  ('Nature''s Spirit', 'Nature''s Spirit', 'nature''s spirit', 490),
  ('Naturehike', 'Naturehike', 'naturehike', 491),
  ('Nautilus', 'Nautilus', 'nautilus', 492),
  ('Navico', 'Navico', 'navico', 493),
  ('Nemo', 'Nemo', 'nemo', 494),
  ('Never Summer', 'Never Summer', 'never summer', 495),
  ('New Balance', 'New Balance', 'new balance', 496),
  ('Nexx', 'Nexx', 'nexx', 497),
  ('Nightforce', 'Nightforce', 'nightforce', 498),
  ('Nike', 'Nike', 'nike', 499),
  ('Nike ACG', 'Nike ACG', 'nike acg', 500),
  ('Nike SB', 'Nike SB', 'nike sb', 501),
  ('Nikon', 'Nikon', 'nikon', 502),
  ('Nitecore', 'Nitecore', 'nitecore', 503),
  ('Nogales', 'Nogales', 'nogales', 504),
  ('Nolan', 'Nolan', 'nolan', 505),
  ('Nordica', 'Nordica', 'nordica', 506),
  ('Nordisk', 'Nordisk', 'nordisk', 507),
  ('Norfin', 'Norfin', 'norfin', 508),
  ('Normal', 'Normal', 'normal', 509),
  ('Norrøna', 'Norrøna', 'norrøna', 510),
  ('Norstream', 'Norstream', 'norstream', 511),
  ('Nova Tour', 'Nova Tour', 'nova tour', 512),
  ('Nunatak', 'Nunatak', 'nunatak', 513),
  ('Nutrabaits', 'Nutrabaits', 'nutrabaits', 514),
  ('O''Neal', 'O''Neal', 'o''neal', 515),
  ('ONA', 'ONA', 'ona', 516),
  ('ORSIS', 'ORSIS', 'orsis', 517),
  ('OSP', 'OSP', 'osp', 518),
  ('Oakley', 'Oakley', 'oakley', 519),
  ('Oboz', 'Oboz', 'oboz', 520),
  ('Ocun', 'Ocun', 'ocun', 521),
  ('Odoland', 'Odoland', 'odoland', 522),
  ('Okuma', 'Okuma', 'okuma', 523),
  ('Old Town', 'Old Town', 'old town', 524),
  ('Olicamp', 'Olicamp', 'olicamp', 525),
  ('Olight', 'Olight', 'olight', 526),
  ('Olympus', 'Olympus', 'olympus', 527),
  ('On Running', 'On Running', 'on running', 528),
  ('OneTigris', 'OneTigris', 'onetigris', 529),
  ('Ontario', 'Ontario', 'ontario', 530),
  ('Opinel', 'Opinel', 'opinel', 531),
  ('Optimus', 'Optimus', 'optimus', 532),
  ('Orca', 'Orca', 'orca', 533),
  ('Ortlieb', 'Ortlieb', 'ortlieb', 534),
  ('Ortovox', 'Ortovox', 'ortovox', 535),
  ('Oru Kayak', 'Oru Kayak', 'oru kayak', 536),
  ('Orvis', 'Orvis', 'orvis', 537),
  ('Osprey', 'Osprey', 'osprey', 538),
  ('Otterbox', 'Otterbox', 'otterbox', 539),
  ('Outdoor Research', 'Outdoor Research', 'outdoor research', 540),
  ('Owner', 'Owner', 'owner', 541),
  ('Oxford', 'Oxford', 'oxford', 542),
  ('Ozark Trail', 'Ozark Trail', 'ozark trail', 543),
  ('PB Products', 'PB Products', 'pb products', 544),
  ('PHD', 'PHD', 'phd', 545),
  ('POC', 'POC', 'poc', 546),
  ('Pa''lante', 'Pa''lante', 'pa''lante', 547),
  ('Panasonic', 'Panasonic', 'panasonic', 548),
  ('Paria Outdoor', 'Paria Outdoor', 'paria outdoor', 549),
  ('Partisan', 'Partisan', 'partisan', 550),
  ('Partridge', 'Partridge', 'partridge', 551),
  ('Patagonia', 'Patagonia', 'patagonia', 552),
  ('Peak Design', 'Peak Design', 'peak design', 553),
  ('Peak Performance', 'Peak Performance', 'peak performance', 554),
  ('Pelican', 'Pelican', 'pelican', 555),
  ('Penn', 'Penn', 'penn', 556),
  ('Pentax', 'Pentax', 'pentax', 557),
  ('Perazzi', 'Perazzi', 'perazzi', 558),
  ('Perception', 'Perception', 'perception', 559),
  ('Petzl', 'Petzl', 'petzl', 560),
  ('Phase One', 'Phase One', 'phase one', 561),
  ('Pieps', 'Pieps', 'pieps', 562),
  ('Plan B', 'Plan B', 'plan b', 563),
  ('Platypus', 'Platypus', 'platypus', 564),
  ('Plum', 'Plum', 'plum', 565),
  ('Point6', 'Point6', 'point6', 566),
  ('Polar', 'Polar', 'polar', 567),
  ('Polisport', 'Polisport', 'polisport', 568),
  ('Pomoca', 'Pomoca', 'pomoca', 569),
  ('Pomoly', 'Pomoly', 'pomoly', 570),
  ('Potable Aqua', 'Potable Aqua', 'potable aqua', 571),
  ('PowerPro', 'PowerPro', 'powerpro', 572),
  ('Prana', 'Prana', 'prana', 573),
  ('Premier', 'Premier', 'premier', 574),
  ('Preston', 'Preston', 'preston', 575),
  ('Preston Innovations', 'Preston Innovations', 'preston innovations', 576),
  ('Primary Arms', 'Primary Arms', 'primary arms', 577),
  ('Primus', 'Primus', 'primus', 578),
  ('Princeton Tec', 'Princeton Tec', 'princeton tec', 579),
  ('Pro-Tec', 'Pro-Tec', 'pro-tec', 580),
  ('Promag', 'Promag', 'promag', 581),
  ('Promedia Gear', 'Promedia Gear', 'promedia gear', 582),
  ('Protech', 'Protech', 'protech', 583),
  ('Pure Fishing', 'Pure Fishing', 'pure fishing', 584),
  ('Quechua', 'Quechua', 'quechua', 585),
  ('RED Digital Cinema', 'RED Digital Cinema', 'red digital cinema', 586),
  ('REDCAMP', 'REDCAMP', 'redcamp', 587),
  ('REI', 'REI', 'rei', 588),
  ('REI Co-op', 'REI Co-op', 'rei co-op', 589),
  ('REVO', 'REVO', 'revo', 590),
  ('RST', 'RST', 'rst', 591),
  ('RTIC', 'RTIC', 'rtic', 592),
  ('Rab', 'Rab', 'rab', 593),
  ('Racetech', 'Racetech', 'racetech', 594),
  ('Radioddity', 'Radioddity', 'radioddity', 595),
  ('Rainy''s', 'Rainy''s', 'rainy''s', 596),
  ('Rapala', 'Rapala', 'rapala', 597),
  ('Ray-Ban', 'Ray-Ban', 'ray-ban', 598),
  ('Raymarine', 'Raymarine', 'raymarine', 599),
  ('Razor', 'Razor', 'razor', 600),
  ('Real Steel', 'Real Steel', 'real steel', 601),
  ('Really Right Stuff', 'Really Right Stuff', 'really right stuff', 602),
  ('Realtree', 'Realtree', 'realtree', 603),
  ('Red Bull', 'Red Bull', 'red bull', 604),
  ('Red Chili', 'Red Chili', 'red chili', 605),
  ('Red Fox', 'Red Fox', 'red fox', 606),
  ('Redington', 'Redington', 'redington', 607),
  ('Regal', 'Regal', 'regal', 608),
  ('Reima', 'Reima', 'reima', 609),
  ('Remington', 'Remington', 'remington', 610),
  ('Rev''It', 'Rev''It', 'rev''it', 611),
  ('Revelate', 'Revelate', 'revelate', 612),
  ('Richa', 'Richa', 'richa', 613),
  ('Ricoh', 'Ricoh', 'ricoh', 614),
  ('Ride', 'Ride', 'ride', 615),
  ('Rig Marole', 'Rig Marole', 'rig marole', 616),
  ('Rio', 'Rio', 'rio', 617),
  ('Rio Products', 'Rio Products', 'rio products', 618),
  ('River Country Products', 'River Country Products', 'river country products', 619),
  ('Robens', 'Robens', 'robens', 620),
  ('Rock Exotica', 'Rock Exotica', 'rock exotica', 621),
  ('Rod Hutchinson', 'Rod Hutchinson', 'rod hutchinson', 622),
  ('Rok Straps', 'Rok Straps', 'rok straps', 623),
  ('Rome', 'Rome', 'rome', 624),
  ('Ross', 'Ross', 'ross', 625),
  ('Rossignol', 'Rossignol', 'rossignol', 626),
  ('Royal Robbins', 'Royal Robbins', 'royal robbins', 627),
  ('Ruger', 'Ruger', 'ruger', 628),
  ('Rukka', 'Rukka', 'rukka', 629),
  ('S-One', 'S-One', 's-one', 630),
  ('SA', 'SA', 'sa', 631),
  ('SIGG', 'SIGG', 'sigg', 632),
  ('SOG', 'SOG', 'sog', 633),
  ('SOL', 'SOL', 'sol', 634),
  ('SW-Motech', 'SW-Motech', 'sw-motech', 635),
  ('Sage', 'Sage', 'sage', 636),
  ('Sako', 'Sako', 'sako', 637),
  ('Salewa', 'Salewa', 'salewa', 638),
  ('Salmo', 'Salmo', 'salmo', 639),
  ('Salomon', 'Salomon', 'salomon', 640),
  ('Samsung', 'Samsung', 'samsung', 641),
  ('Sanrenmu', 'Sanrenmu', 'sanrenmu', 642),
  ('Santa Cruz', 'Santa Cruz', 'santa cruz', 643),
  ('Saucony', 'Saucony', 'saucony', 644),
  ('Savage Arms', 'Savage Arms', 'savage arms', 645),
  ('Savage Gear', 'Savage Gear', 'savage gear', 646),
  ('Sawyer', 'Sawyer', 'sawyer', 647),
  ('Scarpa', 'Scarpa', 'scarpa', 648),
  ('Schmidt & Bender', 'Schmidt & Bender', 'schmidt & bender', 649),
  ('Schrade', 'Schrade', 'schrade', 650),
  ('Schöffel', 'Schöffel', 'schöffel', 651),
  ('Scientific Anglers', 'Scientific Anglers', 'scientific anglers', 652),
  ('Scierra', 'Scierra', 'scierra', 653),
  ('Scorpion', 'Scorpion', 'scorpion', 654),
  ('Scott', 'Scott', 'scott', 655),
  ('Sea to Summit', 'Sea to Summit', 'sea to summit', 656),
  ('Seaguar', 'Seaguar', 'seaguar', 657),
  ('Sector 9', 'Sector 9', 'sector 9', 658),
  ('Segura', 'Segura', 'segura', 659),
  ('Semperfli', 'Semperfli', 'semperfli', 660),
  ('Sensas', 'Sensas', 'sensas', 661),
  ('Shad', 'Shad', 'shad', 662),
  ('Shakespeare', 'Shakespeare', 'shakespeare', 663),
  ('Shark', 'Shark', 'shark', 664),
  ('Shift', 'Shift', 'shift', 665),
  ('Shilton', 'Shilton', 'shilton', 666),
  ('Shimano', 'Shimano', 'shimano', 667),
  ('Shimoda', 'Shimoda', 'shimoda', 668),
  ('Shoei', 'Shoei', 'shoei', 669),
  ('Shuangfeng', 'Shuangfeng', 'shuangfeng', 670),
  ('Sidi', 'Sidi', 'sidi', 671),
  ('Sierra Designs', 'Sierra Designs', 'sierra designs', 672),
  ('Sig Sauer', 'Sig Sauer', 'sig sauer', 673),
  ('Silky', 'Silky', 'silky', 674),
  ('Silva', 'Silva', 'silva', 675),
  ('Simms', 'Simms', 'simms', 676),
  ('Simond', 'Simond', 'simond', 677),
  ('Simply Light Designs', 'Simply Light Designs', 'simply light designs', 678),
  ('Simrad', 'Simrad', 'simrad', 679),
  ('Singing Rock', 'Singing Rock', 'singing rock', 680),
  ('Sitka', 'Sitka', 'sitka', 681),
  ('Six Moon Designs', 'Six Moon Designs', 'six moon designs', 682),
  ('Skypeople', 'Skypeople', 'skypeople', 683),
  ('Slinky Fiber', 'Slinky Fiber', 'slinky fiber', 684),
  ('Smartwool', 'Smartwool', 'smartwool', 685),
  ('Smith', 'Smith', 'smith', 686),
  ('Smith & Wesson', 'Smith & Wesson', 'smith & wesson', 687),
  ('Smith Optics', 'Smith Optics', 'smith optics', 688),
  ('Snow Peak', 'Snow Peak', 'snow peak', 689),
  ('Snowbee', 'Snowbee', 'snowbee', 690),
  ('Snugpak', 'Snugpak', 'snugpak', 691),
  ('So iLL', 'So iLL', 'so ill', 692),
  ('Solar Bat', 'Solar Bat', 'solar bat', 693),
  ('Solar Tackle', 'Solar Tackle', 'solar tackle', 694),
  ('Solarez', 'Solarez', 'solarez', 695),
  ('Sonik', 'Sonik', 'sonik', 696),
  ('Sony', 'Sony', 'sony', 697),
  ('Soto', 'Soto', 'soto', 698),
  ('Source', 'Source', 'source', 699),
  ('SpiderWire', 'SpiderWire', 'spiderwire', 700),
  ('Spidi', 'Spidi', 'spidi', 701),
  ('Spirit River', 'Spirit River', 'spirit river', 702),
  ('Splav', 'Splav', 'splav', 703),
  ('Spot', 'Spot', 'spot', 704),
  ('Spotters', 'Spotters', 'spotters', 705),
  ('Spro', 'Spro', 'spro', 706),
  ('Spyderco', 'Spyderco', 'spyderco', 707),
  ('St. Croix', 'St. Croix', 'st. croix', 708),
  ('Standard Horizon', 'Standard Horizon', 'standard horizon', 709),
  ('Stanley', 'Stanley', 'stanley', 710),
  ('Steiner', 'Steiner', 'steiner', 711),
  ('SteriPen', 'SteriPen', 'steripen', 712),
  ('Sterling', 'Sterling', 'sterling', 713),
  ('Steyr', 'Steyr', 'steyr', 714),
  ('Sticky Baits', 'Sticky Baits', 'sticky baits', 715),
  ('Stihl', 'Stihl', 'stihl', 716),
  ('Stoeger', 'Stoeger', 'stoeger', 717),
  ('Stone Glacier', 'Stone Glacier', 'stone glacier', 718),
  ('Stonfo', 'Stonfo', 'stonfo', 719),
  ('Stormr', 'Stormr', 'stormr', 720),
  ('Streamlight', 'Streamlight', 'streamlight', 721),
  ('Stren', 'Stren', 'stren', 722),
  ('Strider', 'Strider', 'strider', 723),
  ('Strike King', 'Strike King', 'strike king', 724),
  ('Stubai', 'Stubai', 'stubai', 725),
  ('Sufix', 'Sufix', 'sufix', 726),
  ('SunGloves', 'SunGloves', 'sungloves', 727),
  ('Sunline', 'Sunline', 'sunline', 728),
  ('Superior Wilderness Designs', 'Superior Wilderness Designs', 'superior wilderness designs', 729),
  ('SureFire', 'SureFire', 'surefire', 730),
  ('Survival Metrics', 'Survival Metrics', 'survival metrics', 731),
  ('Suunto', 'Suunto', 'suunto', 732),
  ('Swarovski', 'Swarovski', 'swarovski', 733),
  ('Sweet Protection', 'Sweet Protection', 'sweet protection', 734),
  ('TCX', 'TCX', 'tcx', 735),
  ('TSG', 'TSG', 'tsg', 736),
  ('TSL', 'TSL', 'tsl', 737),
  ('TYT', 'TYT', 'tyt', 738),
  ('Tangent Theta', 'Tangent Theta', 'tangent theta', 739),
  ('Tarptent', 'Tarptent', 'tarptent', 740),
  ('Taska', 'Taska', 'taska', 741),
  ('Tatonka', 'Tatonka', 'tatonka', 742),
  ('Tecnica', 'Tecnica', 'tecnica', 743),
  ('Temple Fork', 'Temple Fork', 'temple fork', 744),
  ('Tenaya', 'Tenaya', 'tenaya', 745),
  ('Tenba', 'Tenba', 'tenba', 746),
  ('Terra Nova', 'Terra Nova', 'terra nova', 747),
  ('Teton Sports', 'Teton Sports', 'teton sports', 748),
  ('The North Face', 'The North Face', 'the north face', 749),
  ('Therm-a-Rest', 'Therm-a-Rest', 'therm-a-rest', 750),
  ('Think Tank', 'Think Tank', 'think tank', 751),
  ('Thinking Anglers', 'Thinking Anglers', 'thinking anglers', 752),
  ('Thor', 'Thor', 'thor', 753),
  ('Thorlo', 'Thorlo', 'thorlo', 754),
  ('TiGoat', 'TiGoat', 'tigoat', 755),
  ('Tibor', 'Tibor', 'tibor', 756),
  ('Tiemco', 'Tiemco', 'tiemco', 757),
  ('Tierra', 'Tierra', 'tierra', 758),
  ('Tikka', 'Tikka', 'tikka', 759),
  ('Timbuk2', 'Timbuk2', 'timbuk2', 760),
  ('Timmermade', 'Timmermade', 'timmermade', 761),
  ('Toaks', 'Toaks', 'toaks', 762),
  ('Tom Bihn', 'Tom Bihn', 'tom bihn', 763),
  ('TomTom', 'TomTom', 'tomtom', 764),
  ('Tomshoo', 'Tomshoo', 'tomshoo', 765),
  ('Topo Athletic', 'Topo Athletic', 'topo athletic', 766),
  ('Tops', 'Tops', 'tops', 767),
  ('Toray', 'Toray', 'toray', 768),
  ('Toread', 'Toread', 'toread', 769),
  ('Touratech', 'Touratech', 'touratech', 770),
  ('Trab', 'Trab', 'trab', 771),
  ('Trabucco', 'Trabucco', 'trabucco', 772),
  ('Trackman', 'Trackman', 'trackman', 773),
  ('Tract', 'Tract', 'tract', 774),
  ('Trakker', 'Trakker', 'trakker', 775),
  ('Trangia', 'Trangia', 'trangia', 776),
  ('Trango', 'Trango', 'trango', 777),
  ('Trek Planet', 'Trek Planet', 'trek planet', 778),
  ('Trekkinn', 'Trekkinn', 'trekkinn', 779),
  ('Trekology', 'Trekology', 'trekology', 780),
  ('Trijicon', 'Trijicon', 'trijicon', 781),
  ('Trilene', 'Trilene', 'trilene', 782),
  ('Triple Aught Design', 'Triple Aught Design', 'triple aught design', 783),
  ('Triple Eight', 'Triple Eight', 'triple eight', 784),
  ('Trokar', 'Trokar', 'trokar', 785),
  ('Troy Lee Designs', 'Troy Lee Designs', 'troy lee designs', 786),
  ('Tubbs', 'Tubbs', 'tubbs', 787),
  ('Tucano Urbano', 'Tucano Urbano', 'tucano urbano', 788),
  ('Tungsten Beads', 'Tungsten Beads', 'tungsten beads', 789),
  ('Tyrolia', 'Tyrolia', 'tyrolia', 790),
  ('UCO', 'UCO', 'uco', 791),
  ('UFO', 'UFO', 'ufo', 792),
  ('ULA', 'ULA', 'ula', 793),
  ('US Optics', 'US Optics', 'us optics', 794),
  ('UST', 'UST', 'ust', 795),
  ('Ugly Stik', 'Ugly Stik', 'ugly stik', 796),
  ('Ultralight Outdoor Gear', 'Ultralight Outdoor Gear', 'ultralight outdoor gear', 797),
  ('Ulvang', 'Ulvang', 'ulvang', 798),
  ('Umpqua', 'Umpqua', 'umpqua', 799),
  ('Under Armour', 'Under Armour', 'under armour', 800),
  ('Uniden', 'Uniden', 'uniden', 801),
  ('Union', 'Union', 'union', 802),
  ('Unparallel', 'Unparallel', 'unparallel', 803),
  ('VMC', 'VMC', 'vmc', 804),
  ('Valandré', 'Valandré', 'valandré', 805),
  ('Vango', 'Vango', 'vango', 806),
  ('Vans', 'Vans', 'vans', 807),
  ('Vargo', 'Vargo', 'vargo', 808),
  ('Varivas', 'Varivas', 'varivas', 809),
  ('Vasque', 'Vasque', 'vasque', 810),
  ('Vaude', 'Vaude', 'vaude', 811),
  ('Vedavoo', 'Vedavoo', 'vedavoo', 812),
  ('Veniard', 'Veniard', 'veniard', 813),
  ('Victorinox', 'Victorinox', 'victorinox', 814),
  ('Vision', 'Vision', 'vision', 815),
  ('Vixen', 'Vixen', 'vixen', 816),
  ('Volkl', 'Volkl', 'volkl', 817),
  ('Vortex', 'Vortex', 'vortex', 818),
  ('Wahoo', 'Wahoo', 'wahoo', 819),
  ('Wapsi', 'Wapsi', 'wapsi', 820),
  ('Watershot', 'Watershot', 'watershot', 821),
  ('Weatherby', 'Weatherby', 'weatherby', 822),
  ('Wechsel', 'Wechsel', 'wechsel', 823),
  ('Werner Paddles', 'Werner Paddles', 'werner paddles', 824),
  ('Western Mountaineering', 'Western Mountaineering', 'western mountaineering', 825),
  ('Westin', 'Westin', 'westin', 826),
  ('Whistler', 'Whistler', 'whistler', 827),
  ('Whiting Farms', 'Whiting Farms', 'whiting farms', 828),
  ('Widesea', 'Widesea', 'widesea', 829),
  ('Wigwam', 'Wigwam', 'wigwam', 830),
  ('Wild Country', 'Wild Country', 'wild country', 831),
  ('Wilderness Systems', 'Wilderness Systems', 'wilderness systems', 832),
  ('Wiley X', 'Wiley X', 'wiley x', 833),
  ('William Joseph', 'William Joseph', 'william joseph', 834),
  ('Wimberley', 'Wimberley', 'wimberley', 835),
  ('Winchester', 'Winchester', 'winchester', 836),
  ('Wind Hard', 'Wind Hard', 'wind hard', 837),
  ('Wolfman', 'Wolfman', 'wolfman', 838),
  ('Wotancraft', 'Wotancraft', 'wotancraft', 839),
  ('Wouxun', 'Wouxun', 'wouxun', 840),
  ('Wrangler', 'Wrangler', 'wrangler', 841),
  ('Wulff', 'Wulff', 'wulff', 842),
  ('X-Lite', 'X-Lite', 'x-lite', 843),
  ('Yaesu', 'Yaesu', 'yaesu', 844),
  ('Yaktrax', 'Yaktrax', 'yaktrax', 845),
  ('Yama Mountain Gear', 'Yama Mountain Gear', 'yama mountain gear', 846),
  ('Yates', 'Yates', 'yates', 847),
  ('Yeti', 'Yeti', 'yeti', 848),
  ('Yo-Zuri', 'Yo-Zuri', 'yo-zuri', 849),
  ('Yougle', 'Yougle', 'yougle', 850),
  ('Z-Man', 'Z-Man', 'z-man', 851),
  ('ZPacks China', 'ZPacks China', 'zpacks china', 852),
  ('Zamberlan', 'Zamberlan', 'zamberlan', 853),
  ('Zap-A-Gap', 'Zap-A-Gap', 'zap-a-gap', 854),
  ('Zeiss', 'Zeiss', 'zeiss', 855),
  ('Zero Tolerance', 'Zero Tolerance', 'zero tolerance', 856),
  ('Zoom', 'Zoom', 'zoom', 857),
  ('Zpacks', 'Zpacks', 'zpacks', 858),
  ('f-stop', 'f-stop', 'f-stop', 859),
  ('АиР', 'АиР', 'аир', 860),
  ('Байкал', 'Байкал', 'байкал', 861),
  ('Баск', 'Баск', 'баск', 862),
  ('Век', 'Век', 'век', 863),
  ('Вепрь', 'Вепрь', 'вепрь', 864),
  ('Волжанка', 'Волжанка', 'волжанка', 865),
  ('Златоуст', 'Златоуст', 'златоуст', 866),
  ('Ижмаш', 'Ижмаш', 'ижмаш', 867),
  ('Кизляр', 'Кизляр', 'кизляр', 868),
  ('Лесной Ворон', 'Лесной Ворон', 'лесной ворон', 869),
  ('Магнум', 'Магнум', 'магнум', 870),
  ('Манарага', 'Манарага', 'манарага', 871),
  ('Молот', 'Молот', 'молот', 872),
  ('Наша Марка', 'Наша Марка', 'наша марка', 873),
  ('Ножи Северная корона', 'Ножи Северная корона', 'ножи северная корона', 874),
  ('Нокс', 'Нокс', 'нокс', 875),
  ('Сайга', 'Сайга', 'сайга', 876),
  ('Следопыт', 'Следопыт', 'следопыт', 877),
  ('Сплав', 'Сплав', 'сплав', 878),
  ('ТОЗ', 'ТОЗ', 'тоз', 879),
  ('Тигр', 'Тигр', 'тигр', 880),
  ('Тонар', 'Тонар', 'тонар', 881)
on conflict (name) do update
set
  display_name = excluded.display_name,
  normalized_name = excluded.normalized_name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

alter table if exists public.gear_items
  add column if not exists brand_id uuid;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'gear_items_brand_id_fkey'
      and conrelid = 'public.gear_items'::regclass
  ) then
    alter table public.gear_items
      add constraint gear_items_brand_id_fkey
      foreign key (brand_id) references public.outdoor_brands(id);
  end if;
end $$;

create index if not exists idx_outdoor_brands_display_name on public.outdoor_brands(display_name);
create index if not exists idx_outdoor_brands_normalized_name on public.outdoor_brands(normalized_name);
create index if not exists idx_gear_items_brand_id on public.gear_items(brand_id);

update public.gear_items gi
set
  brand = ob.display_name,
  brand_id = ob.id
from public.outdoor_brands ob
where lower(trim(gi.brand)) = ob.normalized_name
  and ob.id = (
    select first_ob.id
    from public.outdoor_brands first_ob
    where first_ob.normalized_name = lower(trim(gi.brand))
      and first_ob.is_active = true
    order by first_ob.display_order
    limit 1
  )
  and (gi.brand_id is distinct from ob.id or gi.brand is distinct from ob.display_name);

create or replace function public.sync_gear_item_brand_id()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  normalized_brand text;
  matched_brand public.outdoor_brands%rowtype;
begin
  if new.brand_id is not null then
    select * into matched_brand
    from public.outdoor_brands
    where id = new.brand_id
      and is_active = true;

    if found then
      new.brand = matched_brand.display_name;
    else
      new.brand_id = null;
    end if;

    return new;
  end if;

  normalized_brand := lower(trim(coalesce(new.brand, '')));

  if normalized_brand = '' then
    new.brand_id = null;
    new.brand = null;
    return new;
  end if;

  select * into matched_brand
  from public.outdoor_brands
  where normalized_name = normalized_brand
    and is_active = true
  order by display_order
  limit 1;

  if found then
    new.brand_id = matched_brand.id;
    new.brand = matched_brand.display_name;
  else
    new.brand_id = null;
    new.brand = trim(new.brand);
  end if;

  return new;
end $$;

drop trigger if exists sync_gear_item_brand_id_trigger on public.gear_items;
create trigger sync_gear_item_brand_id_trigger
  before insert or update of brand, brand_id on public.gear_items
  for each row
  execute function public.sync_gear_item_brand_id();

alter table public.outdoor_brands enable row level security;

drop policy if exists outdoor_brands_select_all on public.outdoor_brands;
create policy outdoor_brands_select_all
  on public.outdoor_brands for select to anon, authenticated
  using (is_active);
